### ISSUE TITLE
interface get_factory_by_entity returns nil

### ISSUE THREAD

**Issue by kuxynator** [notnotmelon/factorissimo-2-notnotmelon#101]
the error occurs as soon as space-age is active. it works without sapce-age
new game w/o space age > works
open the same save with spage-age > nil
new game w/ space age > nil

entiy is userdata: {name = "factory-1", type = "storage-tank"}

we had the same problem before, but we didn't find out which mod was causing it.
but now we can't ignore spage age ;-)

**Comment by notnotmelon** [comment]
Here is the relevant code

```lua

remote_api.get_factory_by_entity = function(entity)
	if entity == nil then return nil end
	return storage.factories_by_entity[entity.unit_number]
end

```

It seems that the entity userdata requires a unit_number defined.

**Comment by kuxynator** [comment]
there is a unit number
![image](https://github.com/user-attachments/assets/d0e9b7d2-f235-4fb8-b534-f7588a8d18c2)
and I call this in `on_built_entity` event, if that helps

**Comment by notnotmelon** [comment]
I will not fix this. Without your specific addon mod I cannot test and verify if the fix works. For this reason I am not interested in fixing the bug. However I am happy to merge any PRs that resolve this issue.
