### ISSUE TITLE
Molten Copper changing to molten iron with Metallurgic science pack

### ISSUE THREAD

**Issue by Houndspear** [notnotmelon/factorissimo-2-notnotmelon#103]
Hello, 
When building the foundries for metallurgic science packs, the pipe with molten copper gets iron into it as soon as the molten copper is out. It's entering exactly 750 molten iron in the piping system.
Even when emptying the pipes and letting molten copper flow in again, the issue will repeat.
I didn't have this issue when building the metallurgic science packs outside of a factory building.
Save game attached, the building directly above the engineer is the metallurgic science pack one causing the issues.
[Save file](https://github.com/user-attachments/files/17704486/SpaceAgeRail.Test.zip)

**Comment by notnotmelon** [comment]
Not a bug.

You have a iron smelting outputting into a copper pipe.

![image](https://github.com/user-attachments/assets/0302a1bd-7816-4b77-b943-dada4bc21b68)

**Comment by Houndspear** [comment]
Thanks :D I feel like an idiot
