### ISSUE TITLE
Is there a DESTORY or REMOVE button to dispose a factory

### ISSUE THREAD

**Issue by DancingDolphins** [notnotmelon/factorissimo-2-notnotmelon#106]
I Using a mod named trashcan 
it can help me delete some entity in my hand .
some time I delete some factory 
but the factory surface still has that factory 
That's OK but can I dispose some factory from surface ?

as the img
 the factory I have deleted
look the mouse .it appear on earth but I cant find
![image](https://github.com/user-attachments/assets/e072a22e-a911-4173-948b-558a649f6925)

**Comment by notnotmelon** [comment]
Hi, I recommend you to run command `/give-lost-factory-buildings`
