### ISSUE TITLE
Ceiling is too high "Borehole pump"

### ISSUE THREAD

**Issue by marckskl** [notnotmelon/factorissimo-2-notnotmelon#108]
I can't seem to use the Borehole pump in any of my factory buildings. I get the error "Borehole pump can't be built on this surface. The ceiling is too high" whenever i try to place it either on my factory floor or outside. We do use the [Team Starts for Multiplayer](https://mods.factorio.com/mod/team-starts) mod which puts us on non-vanilla planets. I have not tried to fly over to a vanilla planet to try this but I would assume it would work since I have not seen any issues reported with the borehole pump not working. Currently I am trying to do this on Valcanus from Team Starts and it does not work.

**Comment by notnotmelon** [comment]
Thanks for the report. I don't have motivation to fix this issue. Feel free to submit a PR.
