### ISSUE TITLE
Unable to start with factorio 2.0 without space age DLC

### ISSUE THREAD

**Issue by Rugal** [notnotmelon/factorissimo-2-notnotmelon#11]
Hi,

I just upgrade to factorio 2.0 without using `space age` DLC. But unable to use this mod due to this very error.

![image](https://github.com/user-attachments/assets/0d716a4e-bac3-418d-a0dc-aef11ed26cbe)  

I look into your code find that, the ceiling will not enable unless have `space _travel` feature turn on.  

![image](https://github.com/user-attachments/assets/368850d9-da43-443d-9604-a57000415c74)

Now I stuck here, not knowing what to look at next, since not sure where to exclude `space_travel` related logic for `ceiling`.   
I am new to factorio modding, I want to participate in development of this mod. This is a great mod that I would like to devote some of my spare time into.  

Just need some guidance for the next step, wish I could help.

**Comment by Rugal** [comment]
Hi,

Just tested locally that, by commenting below, it works on `factorio 2.0` without `space age`.    

![image](https://github.com/user-attachments/assets/1dc7ff6e-0355-443b-b312-3234988ac9d3)  

But I definitely know this is not the right fix, somehow need to know more about what it is used for.

**Comment by notnotmelon** [comment]
Hi, thanks for the report

This is now fixed as of 1.5.2
