### ISSUE TITLE
Hi! I am having an issue with your mod with oil and it stopping randomly. I have to go in and change each pipe that is connected to the outside from input to output to get it to flow again and then it happens again later. Am I doing something wrong?

### ISSUE THREAD

**Issue by notnotmelon** [notnotmelon/factorissimo-2-notnotmelon#111]
![image](https://github.com/user-attachments/assets/005b1c06-b7cb-4827-a27c-7144a396931c)
![image](https://github.com/user-attachments/assets/75e4694a-dd49-4d6f-bbec-b416a18b3163)

https://cdn.discordapp.com/attachments/1306846919015923794/1306848852124500030/NEW.zip?ex=67382956&is=6736d7d6&hm=8f43607f7715c114bd1399976092c9874129a8330b175649c16488d6c083a8ec&

**Comment by ghuntley** [comment]
Confirming this also happens.
