### ISSUE TITLE
Factory no border/grass off limits

### ISSUE THREAD

**Issue by DiogoHSS** [notnotmelon/factorissimo-2-notnotmelon#115]
Factorio 2.0.15 + Space Age
Factorissimo 3.5.18
+ other mods (could be a conflict?)
![{E35E5C55-C05A-40AA-A261-D994E490F18E}](https://github.com/user-attachments/assets/8404cfcc-8386-450b-9119-a3f44b7c2af2)

**Comment by notnotmelon** [comment]
Please run this command. It may take up to 15 minutes.

```/c for _, surface in pairs(game.surfaces) do if surface.name:find("%-factory%-floor$") or surface.name:find("^factory%-floor%-%d+$") then surface.freeze_daytime = true if remote.interfaces["RSO"] then pcall(remote.call, "RSO", "ignoreSurface", surface.name) end local mgs = surface.map_gen_settings mgs.width = 2 mgs.height = 2 surface.map_gen_settings = mgs local grass_1 = surface.find_tiles_filtered {name = "grass-1"} local new_tiles = {} for _, tile in pairs(grass_1) do table.insert(new_tiles, {name = "out-of-map", position = tile.position}) end surface.set_tiles(new_tiles) end end```

If you prefer to keep achievements, run the command in via this mod (you have to remove /c at the start)
https://mods.factorio.com/mod/some-luaconsole?from=search
