### ISSUE TITLE
shift+left click shortcut to remote view in factorissimo is effectively randomly setting recipes.

### ISSUE THREAD

**Issue by bam13302** [notnotmelon/factorissimo-2-notnotmelon#117]
The shift+ left click shortcut, will clear (or even set if you have a valid one active) the recipe of whatever factory you mouse will be over when you use shift + left click to enter remote view in a factorissimo building.
This can also change a bunch of other stuff (inserter filters, requester chests, and other things), but assemblers and whatnot are bigger so much more likely to be what is under your cursor when you enter remote view.

This can also happen when using that same shortcut to remotely exit the factory.

**Comment by Toberumono** [comment]
@bam13302 were you able to figure out a workaround?

**Comment by bam13302** [comment]
> @bam13302 were you able to figure out a workaround?

best workaround i had was to make sure the factory i was remote viewing into was near the corner of my monitor, so that my cursor would be on the black border of the factory.

one other workaround was to make sure the queued recipe that shift+left click would paste was not one that was compatible with anything in the factory when using the shortcut, roboports were good for this for the most part.

Both of those are kinda shit as they require manual effort every single time you want to enter or leave remote view w/ a factory.

**Comment by DayBr3ak** [comment]
this is annoying behavior, especially since most of the time it just removes the recipe and inserters unload any ingredients on the output belt with the new space age behavior, which in turn clogs the system

**Comment by notnotmelon** [comment]
Default keybind is now changed and allowed remapping.
