### ISSUE TITLE
API factory.inside_surface.planet returns not the physical planet

### ISSUE THREAD

**Issue by kuxynator** [notnotmelon/factorissimo-2-notnotmelon#119]
Shouldn't factory.inside_surface.planet be the real planet, e.g. Nauvis?

![image](https://github.com/user-attachments/assets/88877145-17e4-4521-8adb-65535cb4a81a)

at the moment i parse the planet names from surface.name
but the safe method would be if
factory.inside_surface.planet would return the physical planet to which this surface belongs
at present a planet("nauvis-factory-floor) which should not even exist  is returned

**Comment by notnotmelon** [comment]
I will not make this change. Each of the factory floors are implemented as planets. This has many advantages such as

- Spore pollution types on gleba
- Machine freezing on aquilo
- Shader effects on vulcanus

For this reason, the `planet` field is required to get the associated luaplanet to each factory floor.

I believe to solve your usecase you should use the following command:

`local parent_planet = factory.building.surface.planet`
