### ISSUE TITLE
Prevent Entering Factory while Moving Downward (Or Flying?)

### ISSUE THREAD

**Issue by MaxAstro** [notnotmelon/factorissimo-2-notnotmelon#120]
If it possible, it would be nice if you couldn't enter the factory while moving downwards, or possibly while flying if you can check for that.

The mech armor is very prone to entering factories by accident when you are flying over them.

**Comment by notnotmelon** [comment]
Sorry, I will not do this. The mech armor factory entrance code has already gone through many revisions. It "works" well enough for now. I don't want to look at it anymore.
