### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by PonWer** [notnotmelon/factorissimo-2-notnotmelon#121]
Failed to load mods: Error while loading entity prototype "factory-hidden-construction-roboport" (roboport): roboports that have robot inventory slots must also have charging slots.
Modifications: Factorissimo 3 › Squeak Through 2

**Comment by HollowNaught** [comment]
I'm getting this exact same error message, except it also lists
"combat-mechanics-overhaul (0.7.2)"

Launched the game, no error message, update factorissimo, then I get the above error message

**Comment by notnotmelon** [comment]
Hi, I cant fix this without a mod list

**Comment by VMSolidus** [comment]
> Hi, I cant fix this without a mod list

![image](https://github.com/user-attachments/assets/0803857e-5460-4830-8674-1756f17113f2)

Heya, I've also gotten this error, let me get you my mod list:

![image](https://github.com/user-attachments/assets/5a5afb3b-6e21-4396-9f81-27080d3f8066)

![image](https://github.com/user-attachments/assets/30aa4b15-d197-4a98-9886-908cfaca5e5e)

**Comment by DeschainR** [comment]
I also have the 5Dim mods, disabling New Logistic worked for me.

**Comment by VMSolidus** [comment]
> I also have the 5Dim mods, disabling New Logistic worked for me.

Oh, that worked. Which is a problem because that means I won't be able to continue playing until the compatibility issue is fixed.

**Comment by PonWer** [comment]
I reverted to v3.5.18, which fixed it for now
