### ISSUE TITLE
和综合模组V2  MOD 冲突

### ISSUE THREAD

**Issue by 15068707533** [notnotmelon/factorissimo-2-notnotmelon#122]
在 [综合模组V2](https://mods.factorio.com/mod/VanillaReviseV2) MOD开启“全境电力”的功能时，厂房里的电网无法和厂房外部的电力连接，我询问那个MOD的作者，他说"全境电力”这个功能是游戏本身的命令，并没有脚本之类的，大佬们能否看下是哪里出了问题？

**Comment by notnotmelon** [comment]
Duplicate of https://github.com/notnotmelon/factorissimo-2-notnotmelon/issues/94

**Comment by 15068707533** [comment]
https://github.com/notnotmelon/factorissimo-2-notnotmelon/issues/94   他的问题是两个电线杆之间会冲突，只有一个电线杆时厂房可以正常通电，但是我碰到的问题是厂房内部无法和外部通电，不管外部有多少电线杆，不管外部有多少电源都无法和厂房内部通电。
