### ISSUE TITLE
Remove quality from hidden, inside and connection entities

### ISSUE THREAD

**Issue by FluffyDiscord** [notnotmelon/factorissimo-2-notnotmelon#125]
Mentioned entities are being affected by quality. There is no point to that tho, as you cannot craft, move or destroy them.

For example the power pole inside the factory can be upgraded using a mod like [Upgradeable Quality](https://mods.factorio.com/mod/upgradeable-quality) which then breaks the power delivery and I need to re-build power pole next to the building in order to update/refresh it. Same happens for pipe connections.

I believe this is an issue on this mod's side, as mentioned in the first paragraph, rather than the mentioned UQ mod.

**Comment by notnotmelon** [comment]
Thanks for the report. However I will not fix this. The quality on internal entities serves several important purposes:

- Allow the fluid transfer speed to scale by making the fluid arrow affected by quality.
- Display to the player what is the quality of the current building at a glance.
- Cool factor
