### ISSUE TITLE
Unable to exit Factorissimo Factory within Blueprint Sandbox surface

### ISSUE THREAD

**Issue by PiggyWhiskey** [notnotmelon/factorissimo-2-notnotmelon#128]
https://mods.factorio.com/mod/blueprint-sandboxes/discussion/6752c7a071389f9e72e1b7ac

I initially thought it may be BP Sandboxes safety checks preventing exiting surfaces, but that mod dev says it's not their mod.

Basically entering a Factory while in a BP Sandbox prevents exiting. The god character just moves across the door, and doesn't trigger the exit.

This effectively soft locks the save without console commands as you won't be able to change surface (Function of BP Sandbox) not exit the sandbox (until you can exit the Factory)

**Comment by daz96050** [comment]
Shift-click on the substation to enter/exit  the factory remotely.
