### ISSUE TITLE
Support for moving factorio across surfaces

### ISSUE THREAD

**Issue by FluffyDiscord** [notnotmelon/factorissimo-2-notnotmelon#132]
I built factory on Nauvis, then picked it up and placed it down on Vulcanus. The factory insides still think that it's on Nauvis (as expected, because it was created originally on that Factorissimo surface)

As you might have guessed, as it still thinks its on Nauvis, I cannot craft Turbo belts in it because of it.

Would it be possible to add some kind of automatic option - or manual button - to move factory to another sub-surface? I am aware that there is a recursion to complicate things...

I also just realized that you can take this in the opposite way and cheat by placing down Nauvis factory on Vulcanus, then bypass the space age shipping of materials completely :/

**Comment by notnotmelon** [comment]
Sorry, I cannot add this. There's no way to "reparent" a surface in the modding API.

However,
The factory buildings have a rocket capacity of 0. You should not be able to ship them to vulcanus in the first place.
