### ISSUE TITLE
Picked up buildings, being put down as other buildings.

### ISSUE THREAD

**Issue by abrielmcpierce** [notnotmelon/factorissimo-2-notnotmelon#138]
We just pulled up our buildings making wire, placed the same buildings from our inventory on the ground, and they're blank buildings with blueprints.

![image](https://github.com/user-attachments/assets/eb8b42d4-2f86-4dcc-aeb3-6f32b4ea893d)
![image](https://github.com/user-attachments/assets/d570c553-f265-4fcf-9d49-91ba5b63fc52)
![image](https://github.com/user-attachments/assets/58b78e48-8b61-40bb-8304-f3e24b171a23)

These buildings in the factory map, don't have a green box around them, and they are the buildings that we picked up....
I had to use the /give-lost-factory-buildings command to get them back

![image](https://github.com/user-attachments/assets/03224b48-2e4a-4d7a-8b81-4c776f83885f)

Half these buildings were free somehow. I used the command mentioned earlier. However, it kept giving me the same ones over and over again....
I just did some testing. "LOST" includes buildings on the character.
I picked up a building, used the command, and now have 2 buildings.....

**Comment by notnotmelon** [comment]
Thanks for the report. Unfortunately I cannot fix this without clear, reproducible reproduction steps. For now I recommend to run this command in order to remove grass tiles. It may take up to 15 minutes.

```/c for _, surface in pairs(game.surfaces) do if surface.name:find("%-factory%-floor$") or surface.name:find("^factory%-floor%-%d+$") then surface.freeze_daytime = true if remote.interfaces["RSO"] then pcall(remote.call, "RSO", "ignoreSurface", surface.name) end local mgs = surface.map_gen_settings mgs.width = 2 mgs.height = 2 surface.map_gen_settings = mgs local grass_1 = surface.find_tiles_filtered {name = "grass-1"} local new_tiles = {} for _, tile in pairs(grass_1) do table.insert(new_tiles, {name = "out-of-map", position = tile.position}) end surface.set_tiles(new_tiles) end end```

If you prefer to keep achievements, run the command in via this mod (you have to remove /c at the start)
https://mods.factorio.com/mod/some-luaconsole?from=search
