### ISSUE TITLE
Not enough empty roboport slots available

### ISSUE THREAD

**Issue by qantourisc** [notnotmelon/factorissimo-2-notnotmelon#139]
Possibly a know bug.

**Comment by qantourisc** [comment]
Related to this bug : if you deploy a roboport in this area. The robot's go into the roboport (which then get deleted).
Or if you are quick enough you can grab you some free construction robots.

**Comment by notnotmelon** [comment]
Need more info. How does this case occur? Whats reproduction steps? Can I have log file and save?
