### ISSUE TITLE
Fluidbox volume must be greater than 0.

### ISSUE THREAD

**Issue by kuxynator** [notnotmelon/factorissimo-2-notnotmelon#14]
Failed to load mods: Error while loading entity prototype "factory-inside-pump-input" (pump): Fluidbox volume must be greater than 0.

At ROOT.pump.factory-inside-pump-input.fluid_box
Modifications: Factorissimo 2

v1.5.3

**Comment by notnotmelon** [comment]
Thanks for the report. Fixed now.
