### ISSUE TITLE
bug when installing the mod

### ISSUE THREAD

**Issue by bluemusa** [notnotmelon/factorissimo-2-notnotmelon#15]
i get:
Error while applying migration: Factorissimo 2: middleman-power-pole-surface.lua

Invalid SurfaceIdentification. Surface does not exist.
stack traceback:
	[C]: in function 'delete_surface'
	...otnotmelon__/migrations/middleman-power-pole-surface.lua:1: in main chunk

**Comment by kuxynator** [comment]
@notnotmelon  I'm beginning to wonder who is testing whom ;-)

**Comment by bluemusa** [comment]
"the middleman cant hurt you, he has been removed"

**Comment by Titan-JP** [comment]
Доброго времени суток. Игру крашит

**Comment by Titan-JP** [comment]
![Без имени](https://github.com/user-attachments/assets/4208ecca-16d9-4a05-9f4f-8adf5c03e0bd)
[factorio-current.log](https://github.com/user-attachments/files/17529101/factorio-current.log)
[factorio-dump-current.dmp](https://github.com/user-attachments/files/17529102/factorio-dump-current.dmp)
