### ISSUE TITLE
The factories can be walked from outside

### ISSUE THREAD

**Issue by nikuzo** [notnotmelon/factorissimo-2-notnotmelon#16]
I'm not sure how I did (I think with the hook weapon mod) but zooming out made me look the outside of the factories and you can walk and build outside (If you do, a crash appear after putting some items near the area)

I guess the "bug" can be done with some zoom mods or radars

![image](https://github.com/user-attachments/assets/9c96de14-9b3d-4a88-a0e8-0a66c8809d41)
![image](https://github.com/user-attachments/assets/de69f5d2-94cb-4510-a917-72058dd34be8)

**Comment by nikuzo** [comment]
![image](https://github.com/user-attachments/assets/de69f5d2-94cb-4510-a917-72058dd34be8)

**Comment by NevadaActual** [comment]
To add to this, it looks like refined concrete can be built on the black void tiles? Stone bricks and normal concrete cannot. If this placement is unrelated to the being able to walk outside the factory area, I can make a different issue.
![image](https://github.com/user-attachments/assets/2fe19456-6946-4aa7-8f37-51a4a132077a)

**Comment by notnotmelon** [comment]
> To add to this, it looks like refined concrete can be built on the black void tiles? Stone bricks and normal concrete cannot. If this placement is unrelated to the being able to walk outside the factory area, I can make a different issue.
> 
> EDIT: The refined concrete cannot be removed once placed outside the normal factory bounds. I have a save backup so it's fine, but it's an odd interaction. ![image](https://private-user-images.githubusercontent.com/18467822/380361737-2fe19456-6946-4aa7-8f37-51a4a132077a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjA3MzQsIm5iZiI6MTcyOTkyMDQzNCwicGF0aCI6Ii8xODQ2NzgyMi8zODAzNjE3MzctMmZlMTk0NTYtNjk0Ni00YWE3LThmMzctNTFhNGExMzIwNzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1MjcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMjRlOTI5NDNkNDdkYWE3ZTJjNjZjZmUwOTJkNjA1NmM1YjhhNjI3Y2I1ZjRiODBlNmE1ZDRhMTk4Y2I1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f1-Sgr4OQDhbBflmDxsOyTTm1nePUPZ8uKCk2073yuk)

Please make a new issue. This is unrelated to the original report.
