### ISSUE TITLE
Ошибка при запуске игры! Error when starting the game! 

### ISSUE THREAD

**Issue by Titan-JP** [notnotmelon/factorissimo-2-notnotmelon#17]
![Без имени](https://github.com/user-attachments/assets/4bc1ef74-12e9-466b-b3c6-64ca0cc28562)
[factorio-current.log](https://github.com/user-attachments/files/17529104/factorio-current.log)
[factorio-dump-current.dmp](https://github.com/user-attachments/files/17529105/factorio-dump-current.dmp)

**Comment by notnotmelon** [comment]
You are running factorio version 2.0.7

Please update the game and ensure this error still exists.
