### ISSUE TITLE
Refined concrete can be placed outside factory limits

### ISSUE THREAD

**Issue by NevadaActual** [notnotmelon/factorissimo-2-notnotmelon#18]
Making a new issue as instructed. Tested in the recently updated version of 1.5.8.

Quoting my original post from #16:
> To add to this, it looks like refined concrete can be built on the black void tiles? Stone bricks and normal concrete cannot. If this placement is unrelated to the being able to walk outside the factory area, I can make a different issue.
> 
> EDIT: The refined concrete cannot be removed once placed outside the normal factory bounds. I have a save backup so it's fine, but it's an odd interaction. ![image](https://private-user-images.githubusercontent.com/18467822/380361737-2fe19456-6946-4aa7-8f37-51a4a132077a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjE5MjMsIm5iZiI6MTcyOTkyMTYyMywicGF0aCI6Ii8xODQ2NzgyMi8zODAzNjE3MzctMmZlMTk0NTYtNjk0Ni00YWE3LThmMzctNTFhNGExMzIwNzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMjE2NDI5YjAxNzdjNzk0YTk3MGM1MTU2MzJhMDk1Y2QzODU1YTJlMGE5NGIwMjc1YjMzOGE3Mzg5MThjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tQ2FRYhnFIKVNoo4KgyuLfuTes53kbl5AmDNfQ6esd0)

**Comment by notnotmelon** [comment]
Hmm, interesting issue.

Could you share your `factorio-current.log` file?

**Comment by NevadaActual** [comment]
Sure. This is my log file, where I loaded a save before placing refined concrete out of bounds, placed and walked on it, saved to a new file, then quit the game.
[factorio-current.log](https://github.com/user-attachments/files/17529170/factorio-current.log)

**Comment by notnotmelon** [comment]
This seems to be a problem with [dredgeworks](https://mods.factorio.com/mod/dredgeworks?from=search).

I will report it to them and hopefully the bug is patched.

Thanks for the report.

**Comment by NevadaActual** [comment]
Woah, it affects ribbon worlds as well? That's a wild bug. Thanks for the help, I'll keep an eye out on their end.
