### ISSUE TITLE
Missing Factory Building 1 when tried to place a factory which was picked up earlier.

### ISSUE THREAD

**Issue by Fora-Andy** [notnotmelon/factorissimo-2-notnotmelon#19]
![image](https://github.com/user-attachments/assets/219f383f-0a73-4a71-aa51-4148102cc430)
Not sure conflict reason, I've pathched a lot of mods.

**Comment by Fora-Andy** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17529397/factorio-current.log)
There is the log file.

**Comment by notnotmelon** [comment]
Update factorio to >=2.0.11
