### ISSUE TITLE
Game Crash when Factory is deconstructed without clearing Factory overlay controller first 

### ISSUE THREAD

**Issue by madstorp** [notnotmelon/factorissimo-2-notnotmelon#20]
Error while running event factorissimo-2-notnotmelon::on_player_mined_entity (ID 68)
__factorissimo-2-notnotmelon__/control.lua:494: attempt to concatenate field '?' (a nil value)
stack traceback:
	__factorissimo-2-notnotmelon__/control.lua:494: in function 'generate_factory_item_description'
	__factorissimo-2-notnotmelon__/control.lua:522: in function <__factorissimo-2-notnotmelon__/control.lua:509>

**Comment by notnotmelon** [comment]
What sort of item did you put in the controller

**Comment by madstorp** [comment]
Crude oil was one of the entities listed om the controller before the crash occurred.
