### ISSUE TITLE
Suggestion: Change Icons for 'mined' factory buildings.

### ISSUE THREAD

**Issue by JamieRCHI** [notnotmelon/factorissimo-2-notnotmelon#25]
Change the colors of the Icons used for factory buildings that were mined to differentiate between unused factory buildings that have never been placed.
Attached is a sample Icon picture.

factory.lua is changed as shown below at line 61.
icon = F .. "/graphics/icon/factory-1b.png",

The new Icon.
[factorissimo_factory.lua_change.zip](https://github.com/user-attachments/files/17531964/factorissimo_factory.lua_change.zip)

**Comment by notnotmelon** [comment]
The factorio mod discussions have no potential to be automated with CICD bug tracking. Thus they will remain closed.

**Comment by notnotmelon** [comment]
I have implemented your suggestion. Thank you.

![image](https://github.com/user-attachments/assets/86c20a99-4980-44e0-9761-eb716861d52b)
