### ISSUE TITLE
Failed to load mods: Error while loading entity prototype "factory-1" (storage-tank): Too many parameters for localised string: 256 > 20 (limit). in property tree at ROOT.storage-tank.factory-1.factoriopedia_description[1] Modifications: Factorissimo 2

### ISSUE THREAD

**Issue by LoganDark** [notnotmelon/factorissimo-2-notnotmelon#27]
![image](https://github.com/user-attachments/assets/e5ee64fd-d9d1-4b71-b5b6-85fd509d51e9)

I am using the mod version 1.9.0 that was uploaded a few minutes ago, on Factorio 2.0.11

**Comment by Higuys153** [comment]
Same 1.9.1 20 mins ago

**Comment by Higuys153** [comment]
dev said mods that add extra quality levels can break it
