### ISSUE TITLE
Requester chest's inventory  within building is not shared with passive chest's inventory outside of building

### ISSUE THREAD

**Issue by garfu** [notnotmelon/factorissimo-2-notnotmelon#28]
It appears a requester chest's inventory within a building is not shared with passive chest outside of a building.

Having just played pre SA, this functionality seemed straightforward, maybe I'm missing something? I have the research for chest item passing, that isn't the issue.

The requester chest's inventory appears emptied out within the building so it is constantly requesting items while infinitely filling the passive provider chest linked to it outside of the building. 

Could have sworn it worked differently in the previous non-SA version... but unsure. Thanks!
![image](https://github.com/user-attachments/assets/1a7bb044-a23c-44f0-8e35-255121ca803a)
![image](https://github.com/user-attachments/assets/43eddb18-c7e9-4326-80b8-bc7f8159e501)

**Comment by notnotmelon** [comment]
Set the chest connection to balance mode.

**Comment by garfu** [comment]
Same for outside to in:
![image](https://github.com/user-attachments/assets/c21cb7a2-5621-4848-b9d1-7c3457c92b0e)
![image](https://github.com/user-attachments/assets/e0749bf7-b9fb-420a-b075-db2b85165e80)

**Comment by garfu** [comment]
Just saw your comment, thanks. Didn't have to do that in the non-forked version. My bad.

**Comment by notnotmelon** [comment]
Factorissimo has always worked this way.
The only difference being that "balance mode" was the default option previously.
