### ISSUE TITLE
MK1 Buildings cant be handcrafted anymore

### ISSUE THREAD

**Issue by rouvenw93** [notnotmelon/factorissimo-2-notnotmelon#31]
after updating to v3.1.7 MK1 buildings cant be handcrafted anymore.

**Comment by notnotmelon** [comment]
I will mark this as "not a bug"

This change was made to allow the factory building to be crafted in the foundry. Previously it was way to expensive to make legendary factorissimos. Foundry recipes cannot be handcrafted. 

This only exists in space age, vanilla 2.0 is not effected.
