### ISSUE TITLE
Can't re-place picked up factory building

### ISSUE THREAD

**Issue by gamingvirtue** [notnotmelon/factorissimo-2-notnotmelon#34]
Just as stated in the title (and shown in the picture below), picking up a building results in it being impossible to place back down again. Attempting to use /give-lost-factory-buildings also doesn't fix this problem, instead just duplicating the unplaceable buildings in the inventory.

There are no errors in the log or the console, either, so this is about the most I can provide regarding the issue.

![image](https://github.com/user-attachments/assets/0e6bd385-a4ff-4a1e-a8b5-64db01358274)

**Comment by notnotmelon** [comment]
Update factorio.

**Comment by gamingvirtue** [comment]
Peculiar...could've sworn it was updated already, but I suppose Steam was being stupid. At least it's not a problem anymore.
