### ISSUE TITLE
v3.3.0 and v3.3.1 are causing a ctd

### ISSUE THREAD

**Issue by tigartar** [notnotmelon/factorissimo-2-notnotmelon#38]
[factorio-current.log](https://github.com/user-attachments/files/17552106/factorio-current.log)

Not sure what exactly is causing the crash to happen but it crashes during the initial loading screen during building prototypes

**Comment by FelixGrafschmidt** [comment]
Same here
[factorio-dump-previous.dmp](https://github.com/user-attachments/files/17552887/factorio-dump-previous.dmp)

**Comment by Tenderroast** [comment]
same problem, updated mods, and this mod, and Reverse Factory were the only ones that needed update, and now the game cant go past startup screen

**Comment by Tenderroast** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17553171/factorio-current.log)

**Comment by FelixGrafschmidt** [comment]
The issue also occurs when loading no other mods beside Factorissimo.
[factorio-current.log](https://github.com/user-attachments/files/17553235/factorio-current.log)
[factorio-dump-current.dmp](https://github.com/user-attachments/files/17553237/factorio-dump-current.dmp)

**Comment by seertenedos** [comment]
confirmed the same and removing the mod stops it so 100% related to this mod

**Comment by BurntAussieTyre** [comment]
I'm crashing when game is building prototypes. 3.2.1 was last working version for me.
Logs for 3.3.0 and 3.3.1:

[factorio-current.3.3.0.log](https://github.com/user-attachments/files/17553392/factorio-current.3.3.0.log)

[factorio-current.3.3.1.log](https://github.com/user-attachments/files/17553394/factorio-current.3.3.1.log)

**Comment by DarklordAzazel** [comment]
same issue. downgrade to 3.2.1 worked for now.

**Comment by ghosthrid001** [comment]
same issue, after update mod ctd

**Comment by dirkschut** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17556339/factorio-current.log)
[factorio-dump-previous.dmp](https://github.com/user-attachments/files/17556341/factorio-dump-previous.dmp)
Also CTD-ing on startup after updating here as well. Here's the log and dmp file :)

**Comment by notnotmelon** [comment]
Sorry, I was using some features in the experimental version of factorio. I forgot to update the minimum required version.
