### ISSUE TITLE
Factorissimo 3 crashes on startup.

### ISSUE THREAD

**Issue by NMayerOnyx** [notnotmelon/factorissimo-2-notnotmelon#40]
Factorissimo 3 crashes on startup.

Happens when it is loaded alone as well.

Here is the crash log.
https://pastebin.com/0e44frgb

Game version 2.0.11
Mod version 3.3.1

**Comment by marzboi** [comment]
I can confirm I am experiencing the same error after updating.

**Comment by cynricng** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17555138/factorio-current.log)

Was just playing a while ago. Restarted game, updated the mod, and now it crashes on startup.

Tried deleting mods and reinstalling the mod, still crashes.


`   2.183 Checksum of WideChests: 1638172134
   2.183 Checksum of factorissimo-2-notnotmelon: 1996609867
   2.323 Error CrashHandler.cpp:641: Received SIGSEGV
Factorio crashed. Generating symbolized stacktrace, please wait ...
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\libraries\StackWalker\StackWalker.cpp(924): StackWalker::ShowCallstack
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Util\Logger.cpp(337): Logger::writeStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Util\Logger.cpp(379): Logger::logStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Util\CrashHandler.cpp(185): CrashHandler::writeStackTrace
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Util\CrashHandler.cpp(654): CrashHandler::SignalHandler
minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp(219): _seh_filter_exe
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(304): `__scrt_common_main_seh'::`1'::filt$0
D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp(389): __C_specific_handler
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFC874D517F)
00007FFC874D517F (ntdll): (filename not available): _chkstk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFC8744E856)
00007FFC8744E856 (ntdll): (filename not available): RtlFindCharInUnicodeString
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFC874D416E)
00007FFC874D416E (ntdll): (filename not available): KiUserExceptionDispatcher
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Entity\RoboportPrototype.cpp(129): RoboportPrototype::RoboportPrototype
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\PrototypeLoader.hpp(31): _Closure_wrapper_61c5dda9_670::<lambda_invoker_cdecl>
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\ID\PrototypeList.cpp(28): PrototypeList<EntityPrototype>::executeLoader
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\PrototypeLoader.cpp(284): PrototypeLoader::loadPrototypeForType
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\PrototypeLoader.cpp(71): PrototypeLoader::loadPrototypes
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\ModManager.cpp(955): ModManager::loadModPrototypes
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\ModManager.cpp(1366): ModManager::processMods
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Data\ModManager.cpp(579): ModManager::loadData
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\GlobalContext.cpp(507): GlobalContext::init
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\MainLoop.cpp(288): MainLoop::run
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Main.cpp(1325): fmain
C:\Users\build\AppData\Local\Temp\factorio-build-Yo9xJd\src\Main.cpp(1347): wmain
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFC8522257D)
00007FFC8522257D (KERNEL32): (filename not available): BaseThreadInitThunk`

**Comment by cynricng** [comment]
If someone else wants to keep playing while the mod creating fixes the mod.

I downloaded an older version of the mod and overwrite it and seems to work fine. 

I downloaded 3.2.1 from the mod page, went into "User\AppData\Roaming\Factorio\mods" and replaced the zip file

**Comment by Arlack** [comment]
Yep, same here. Game will not load with the latest update, even alone.

**Comment by Wolkte** [comment]
Same here installed new update and now game crashes

**Comment by DancingDolphins** [comment]
you can downgrade factorissimo to 3.2.X .
or you can try game version 2.0.12 (which steam right click game set to experimental 2.0.12 )  but DOT NOT research Robot thing
