### ISSUE TITLE
Crash when destorying the mod's building

### ISSUE THREAD

**Issue by YR1044** [notnotmelon/factorissimo-2-notnotmelon#41]
game version 2.0.12
mod version 3.3.1

 151.347 Info ClientSynchronizer.cpp:319: Latency changed to (20)
 156.348 Info ClientSynchronizer.cpp:319: Latency changed to (11)
 166.613 Info ClientSynchronizer.cpp:319: Latency changed to (12)
 186.682 Info ClientSynchronizer.cpp:319: Latency changed to (11)
 191.681 Info ClientSynchronizer.cpp:319: Latency changed to (14)
 204.820 Error CrashHandler.cpp:503: Exception Code: c0000005, Address: 0x00007ff7880ba9ef
ModuleBase: 0x00007ff787660000, ImageSize: 02806000, RelativeAddress: 00a5a9ef
 204.820 Error CrashHandler.cpp:509: Access Violation: Read at address 00000000000002F8
 204.820 Error CrashHandler.cpp:523: Exception Context:
rax=000002652424f5f0, rbx=0000026523e0d600, rcx=0000000000000000,
rdx=0000000000000000, rsi=0000000000000000, rdi=0000026523e0d638,
rip=00007ff7880ba9ef, rsp=000000cc756ff350, rbp=000000000000006d,
 r8=000002657e7d58f0,  r9=0000026523e0d600, r10=00000266b93c6680,
r11=000000cc756ff2f0, r12=00000266caa31540, r13=00000266f05cf580,
r14=00000266f05cf580, r15=0000026523e0d5b0
 204.820 Crashed in D:\Program Files\Factorio\bin\x64\factorio.exe (0x00007ff787660000 - 0x00007ff789e66000)
Factorio crashed. Generating symbolized stacktrace, please wait ...
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\libraries\StackWalker\StackWalker.cpp(924): StackWalker::ShowCallstack
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Util\Logger.cpp(337): Logger::writeStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Util\Logger.cpp(379): Logger::logStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Util\CrashHandler.cpp(185): CrashHandler::writeStackTrace
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Util\CrashHandler.cpp(552): CrashHandler::SehHandler
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF36CB21C)
00007FFEF36CB21C (KERNELBASE): (filename not available): UnhandledExceptionFilter
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C997FD)
00007FFEF5C997FD (ntdll): (filename not available): RtlCopyMemory
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C7F687)
00007FFEF5C7F687 (ntdll): (filename not available): _C_specific_handler
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C9517F)
00007FFEF5C9517F (ntdll): (filename not available): _chkstk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C0E856)
00007FFEF5C0E856 (ntdll): (filename not available): RtlFindCharInUnicodeString
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C9416E)
00007FFEF5C9416E (ntdll): (filename not available): KiUserExceptionDispatcher
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Item\ItemStack.cpp(401): ItemStack::drawItemAndQuality
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Entity\ItemEntity.cpp(46): ItemEntity::draw
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Graphics\EntityRenderer.cpp(416): EntityRenderer::prepareRow
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Graphics\EntityRenderer.cpp(299): EntityRenderer::threadJob
C:\Users\build\AppData\Local\Temp\factorio-build-6d0Nrd\src\Util\WorkerThread.cpp(70): WorkerThread::loop
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\thread(56): std::thread::_Invoke<std::tuple<void (__cdecl RouterBase::*)(void),ClientRouter *>,0,1>
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *),1>
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF51C257D)
00007FFEF51C257D (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF5C4AF08)
00007FFEF5C4AF08 (ntdll): (filename not available): RtlUserThreadStart
Stack trace logging done
 207.606 Error CrashHandler.cpp:190: Map tick at moment of crash: 2378583
 207.703 Info CrashHandler.cpp:318: Executable CRC: 512094220
 207.703 Error Util.cpp:95: Unexpected error occurred. If you're running the latest version of the game you can help us solve the problem by posting the contents of the log file on the Factorio forums.
Please also include the save file(s), any mods you may be using, and any steps you know of to reproduce the crash.
 216.119 Uploading log file
 216.253 Error CrashHandler.cpp:270: Heap validation: success.
 216.254 Creating crash dump.
 216.594 CrashDump success

**Comment by notnotmelon** [comment]
I need more info. Can you send the full factorio-current.log with savefile?

**Comment by notnotmelon** [comment]
Closing this.

**Comment by YR1044** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17575462/factorio-current.log)
[路灯挂件加工厂.zip](https://github.com/user-attachments/files/17575465/default.zip)

**Comment by YR1044** [comment]
@notnotmelon sorry for the delay, just test in newest mod version 3.3.12 and the bug still exist
