### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by DancingDolphins** [notnotmelon/factorissimo-2-notnotmelon#45]
模组「Factorissimo 3 (3.3.4)」引发了无法恢复的错误。
请向模组作者反馈此错误。

Error while running event factorissimo-2-notnotmelon::on_player_mined_entity (ID 68)
__factorissimo-2-notnotmelon__/script/roboport.lua:80: Arguments count error for 'spill_item_stack': Expected 1 argument but 2 were given
stack traceback:
	[C]: in function 'spill_item_stack'
	__factorissimo-2-notnotmelon__/script/roboport.lua:80: in function 'cleanup_factory_exterior'
	__factorissimo-2-notnotmelon__/control.lua:356: in function 'cleanup_factory_exterior'
	__factorissimo-2-notnotmelon__/control.lua:640: in function <__factorissimo-2-notnotmelon__/control.lua:635>

**Comment by notnotmelon** [comment]
Update the mod.
