### ISSUE TITLE
Building contents are destroyed if placed using Auto Ghost Builder mod

### ISSUE THREAD

**Issue by John73John** [notnotmelon/factorissimo-2-notnotmelon#49]
I use the Auto Ghost Builder mod (https://mods.factorio.com/mod/AutoGhostBuilder) to help fill in ghosts when I don't have construction robots yet. I don't know if the issue is on your end or theirs, but here's what happens and how to reproduce it:

1. Make 2 factory buildings and place them on the map.
2. Go in the first building and build some stuff.
3. Go outside and pick up the first building (the one with the stuff you built).
4. Copy the 2nd (empty) building and paste it nearby.
5. If Auto Ghost Builder wasn't turned on, turn it on and mouse over the ghost. The building from your inventory with the stuff you built will be placed.
6. Go inside and notice that the stuff you built has disappeared.

**Comment by notnotmelon** [comment]
https://mods.factorio.com/mod/AutoGhostBuilder/discussion/6723b367801e65ec712444fe

**Comment by notnotmelon** [comment]
Closing this as resolved by 3rd party.
