### ISSUE TITLE
Hope Ctrl+Right click  and Ctrl+Left click can copy ALT mode display inf.

### ISSUE THREAD

**Issue by DancingDolphins** [notnotmelon/factorissimo-2-notnotmelon#51]
I have some same factory copy from blue print .
after I finished the build .I want to display the factory purpose l
I know I can set the display controller inside the factory building to display icon for ALT mode
but what I  struggled .which is I have to set the display controller One by One .

I try to use Ctrl+Right click and Ctrl+Left click but no use.
wish add this function make Ct.R+Ct.L useful?

**Comment by notnotmelon** [comment]
This is already a feature. https://files.catbox.moe/aeaq4v.mp4
