### ISSUE TITLE
Compact circuits issue when copy factorissimo

### ISSUE THREAD

**Issue by seertenedos** [notnotmelon/factorissimo-2-notnotmelon#53]
If you take a  direct blueprint copy of a populated [Compact circuits](https://mods.factorio.com/mod/compaktcircuit) and place it in factorissimo it works great but if you copy a factorissiom that contains Compact Circuits then when the inside buildings are made all the compact circuits haves no state and are missing all their design. You need to delete the inside of factorissimo and copy from another building and place it inside again to fix it.

**Comment by notnotmelon** [comment]
https://mods.factorio.com/mod/compaktcircuit/discussion/6722b55f1ed5bd37386ff020

**Comment by notnotmelon** [comment]
Resolved in https://github.com/notnotmelon/factorissimo-2-notnotmelon/commit/05f96d32e69fcf561d6b2d9e2fd4a0dfa1514b89
