### ISSUE TITLE
Roboport built in supply cheat does not copy settings 

### ISSUE THREAD

**Issue by seertenedos** [notnotmelon/factorissimo-2-notnotmelon#54]
If you set the filter to basically disable the supply chest for the built in roboport then copy the whole building then the new factorissimo will not have the same settings on the supply chest for the robot port. Main reason is that if you are using logistic robots in there and logic centers to push items in, out and to machines then a large part of them end up stick in the built in supply chest instead of going in out of the factory or being sent to machines as desired.

**Comment by notnotmelon** [comment]
Reopening this as my "fix" now breaks the decon planner and upgrade planner.
