### ISSUE TITLE
Factory surface is surrounded by grass

### ISSUE THREAD

**Issue by Salvar** [notnotmelon/factorissimo-2-notnotmelon#56]
I believe this was fixed in some earlier version, but for some reason my surface is still grassy. I can walk outside and even jog over to a different building and exit from there.

Running on latest version, 3.4.1

![image](https://github.com/user-attachments/assets/3a14d6bc-a56d-44b3-8fd0-bc01ccf0a3d3)

**Comment by notnotmelon** [comment]
Please run this command:

`/c for _, surface in pairs(game.surfaces) do
    if surface.name:find("%-factory%-floor$") or surface.name:find("^factory%-floor%-%d+$") then
        surface.freeze_daytime = true
        surface.daytime = 0.5
        if remote.interfaces["RSO"] then
            pcall(remote.call, "RSO", "ignoreSurface", surface.name)
        end
        local mgs = surface.map_gen_settings
        mgs.width = 2
        mgs.height = 2
        surface.map_gen_settings = mgs
        local grass_1 = surface.find_tiles_filtered {name = "grass-1"}
        local new_tiles = {}
        for _, tile in pairs(grass_1) do
            table.insert(new_tiles, {name = "out-of-map", position = tile.position})
        end
        surface.set_tiles(new_tiles)
    end
end`
