### ISSUE TITLE
Factorio crashes when Biters attack Factorrismo-Buildings. 

### ISSUE THREAD

**Issue by ocubist** [notnotmelon/factorissimo-2-notnotmelon#57]
## Details

Took me a while to find out, but I was able to reproduce the error: 

Factorio crashes when Biters attack Factorrismo-Buildings.

## Crash-Log

[factorio-previous.log](https://github.com/user-attachments/files/17578826/factorio-previous.log)

## Personal Comment

I was really looking forward using Factorrismo for this run. Used it before (Version 2, I think), but I guess, I have to restart my game without it 😢

**Comment by notnotmelon** [comment]
Thanks for the report. This is an upstream issue. I have reported this to the vanilla devs at wube.

https://forums.factorio.com/viewtopic.php?f=7&t=118677

**Comment by notnotmelon** [comment]
For now, I recommend as a workaround to build better defenses around the factory building.

**Comment by daz96050** [comment]
Couldn't you also temporarily enable invincible buildings? Or is that permanent?

**Comment by notnotmelon** [comment]
Good idea. That's a mod setting.
