### ISSUE TITLE
[3.3.9] - Mech suit "hover" mode with exoskeletons makes entering factory buildings difficult

### ISSUE THREAD

**Issue by PiggyWhiskey** [notnotmelon/factorissimo-2-notnotmelon#58]
The Mech suit hover mode "jumps" over the entrance. Even when trying to line up directly and walking straight up, it makes it very tricky to attempt to enter buildings. 

Some times walking from the top, entering hover mode, and crossing the threshold will also randomly enter the building.

**Comment by notnotmelon** [comment]
This is now fixed. The ability to enter from above is an intended feature.
