### ISSUE TITLE
chest connections seem to be broken

### ISSUE THREAD

**Issue by rouvenw93** [notnotmelon/factorissimo-2-notnotmelon#62]
sometimes items transfer to the construction chest, sometimes to somewhere unknown, but not to the connected chest

**Comment by notnotmelon** [comment]
Hi, are you on the latest version?

This was already fixed here: https://github.com/notnotmelon/factorissimo-2-notnotmelon/issues/55

**Comment by notnotmelon** [comment]
Possibly related: https://github.com/notnotmelon/factorissimo-2-notnotmelon/issues/65
