### ISSUE TITLE
Connection to factory building stuck as chest connections

### ISSUE THREAD

**Issue by Patrix96** [notnotmelon/factorissimo-2-notnotmelon#65]
Some connections to building seems to get stuck as chest connections, even without anything connected to them, while some of them work correctly.
I tried to destroy the factory building and placing it again, but connections are still stuck the same way.

![427520_13](https://github.com/user-attachments/assets/32762502-96c6-49d9-b41e-2b01f59e7364)

**Comment by notnotmelon** [comment]
Thanks, this is now fixed.
My fix does not retroactively prevent these ghosts from forming, but it should prevent new ghosts.
