### ISSUE TITLE
[3.3.12] is there a way to turn off the roboport that is built inside the factory from stealing my construction bots?

### ISSUE THREAD

**Issue by DoomSquirter** [notnotmelon/factorissimo-2-notnotmelon#67]
factorissimo-2-notnotmelon_3.3.12

when I place a factory down, 10 of my construction bots go wololo and join the factory in the roboport there

Is there a way to toggle that behavior on/off?

**Comment by notnotmelon** [comment]
This is non-trival to fix. Would simply setting a personal logistics request for construction robots resolve the issue?

**Comment by notnotmelon** [comment]
Closing this as resolved.

**Comment by DoomSquirter** [comment]
I really don't understand what you're saying tho

when I place down a roboport, there is no automatic robots going to the roboport

but again, if I place down a factory, there is.

it's putting the robots in there as workers, not items.  I don't see how adding a request for bots will work (again, it's not exposing them as items, but they are workers instead)

I assume you added this behavior to the roboport in the factory for some reason?

**Comment by DoomSquirter** [comment]
and yeah I just tested and no, it does not work (logistic request)

**Comment by DoomSquirter** [comment]
@notnotmelon you only gave me like 2.5 hrs to respond before you closed this.  Is this the end of the discussion here?

It'd really be nice to have a config option for this, or at the very least, understand why it does this.  please?
