### ISSUE TITLE
Issue with building factory 2

### ISSUE THREAD

**Issue by schytt58** [notnotmelon/factorissimo-2-notnotmelon#7]
Mod Factorissimo 2 (2.0.0) způsobil neopravitelnou chybu.
Prosím nahlaš tuto chybu autorovi modu.

Error while running event factorissimo-2-notnotmelon::on_built_entity (ID 6)
LuaGameScript doesn't contain key max_electric_pole_supply_area_distance.
stack traceback:
	[C]: in function '__index'
	__factorissimo-2-notnotmelon__/script/electricity.lua:53: in function 'update_power_connection'
	__factorissimo-2-notnotmelon__/control.lua:268: in function 'create_factory_exterior'
	__factorissimo-2-notnotmelon__/control.lua:455: in function 'create_fresh_factory'
	__factorissimo-2-notnotmelon__/control.lua:462: in function 'handle_factory_placed'
	__factorissimo-2-notnotmelon__/control.lua:487: in function <__factorissimo-2-notnotmelon__/control.lua:480>

![obrázek_2024-10-23_164627754](https://github.com/user-attachments/assets/96a4726c-93a6-4b7e-af13-84ec73c56213)

**Comment by notnotmelon** [comment]
The mod is not ready for production use.
