### ISSUE TITLE
Factory interior aligned such that I can leave it and place items.

### ISSUE THREAD

**Issue by grickit** [notnotmelon/factorissimo-2-notnotmelon#70]
![image](https://github.com/user-attachments/assets/510f8c26-3228-4699-bdef-c104b97db370)

I'm not sure what the process is to create/recreate these conditions. But this was an existing factory filled with smelters that I placed down over top of a blueprinted external area that called for a factory building.

That is the only difference I can think of between this factory and all my other ones and I know that in version 3 you put a lot of work into copying/blueprinting.

1. Copy and paste an area of the outside world that contains a factory building
2. Pick up and place an existing factory into that pasted blueprint area

I'm on the latest version of the game and the following mods are enabled:

- Base mod 2.0.13
- Elevated rails 2.0.13
- Quality 2.0.13
- Space age 2.0.13
- Factorio Library 0.15.0
- Factorissimo 3.4.14
- Far Reach 2.0.0
- Fluid memory storage 1.7.5
- Loaders modernized 0.6.2
- Memory storage 1.6.4
- Warehousing mod 0.6.0

I don't know if uploading the save file would help or if you'd just be annoyed by needing to install all these other mods to look at it. Let me know if there's anything else I can provide.

**Comment by grickit** [comment]
Okay I'm actually experiencing this problem with entirely new freshly crafted and placed factories as well.

**Comment by notnotmelon** [comment]
Please run this command

`Please run this command:

/c for _, surface in pairs(game.surfaces) do if surface.name:find("%-factory%-floor$") or surface.name:find("^factory%-floor%-%d+$") then surface.freeze_daytime = true surface.daytime = 0.5 if remote.interfaces["RSO"] then pcall(remote.call, "RSO", "ignoreSurface", surface.name) end local mgs = surface.map_gen_settings mgs.width = 2 mgs.height = 2 surface.map_gen_settings = mgs local grass_1 = surface.find_tiles_filtered {name = "grass-1"} local new_tiles = {} for _, tile in pairs(grass_1) do table.insert(new_tiles, {name = "out-of-map", position = tile.position}) end surface.set_tiles(new_tiles) end end`
