### ISSUE TITLE
[3.5.5] factory roboport is somehow deleting bots if you don't give them bots initially (on loading save)

### ISSUE THREAD

**Issue by DoomSquirter** [notnotmelon/factorissimo-2-notnotmelon#75]
I had previously open #67 and this is slightly about that issue but something different too

so, you place a factory down and it steals 10 of my construction bots
I go in, take back my bots cause I haven't even made a logistic network or anything and I really didn't intend to have to maintain this when I did the research, but here I am

so I started factorio up a half hour ago, saw updates, updated.  
now running factorissimo-2-notnotmelon_3.5.5

as soon as I load the game, I see my bots head to the nearby factory
then I get 6 alerts saying all my factories are missing 1 construction bot
I go back into the factory and get my bots but there aren't 10 but 6
I had a stack of 50 now 39
so I visit each factory and grab the bots it steals from me but in the end after visiting all 7 of my factories, I'm still left with 39 bots

so they went ... somewhere?  

So again, is there some way to disable this behavior?  If I need bots in a factory, I'm more than capable of just putting them in there myself.  

Doesn't need a gui element, just needs a config option.  Is that still "non trivial" to fix?

I have 50 bots here
![image](https://github.com/user-attachments/assets/0d66c257-90a4-49da-bed0-ab8503a77c79)
![image](https://github.com/user-attachments/assets/634f13cd-94fb-4af7-b3a1-29c4d9ba3c16)

so I reloaded my save to get those screenshots and this time it took 10 and I got 10 back

so tbh I don't know how my initial load and subsequent running around lost me 11 bots in total
but also, I have these alerts stuck now till I visit each factory

I may have run into the factory while the bots were still approaching.  not even sure at this point

**Comment by DoomSquirter** [comment]
so I just went around to my other factories cause I couldn't avoid it really

went into each one.  when I was all done, I am now missing 5 bots that I have no idea where they went.  I've now checked all the factories a second time to verify.

**Comment by notnotmelon** [comment]
Thanks for your report. Sorry for prematurely closing #67 
I currently have no way to see notifications for new messages on closed bug reports.

**Comment by notnotmelon** [comment]
> I'm more than capable of just putting them in there myself.

The whole point is to have it request bots when you are in remote view on another planet.

**Comment by notnotmelon** [comment]
> I had a stack of 50 now 39 so I visit each factory and grab the bots it steals from me but in the end after visiting all 7 of my factories, I'm still left with 39 bots

Sorry about this. However it seems you encountered this bug over multiple hours. In this situation it's impossible for me to reproduce the edge case. If you can give me short, reliable reproduction steps then I am happy to fix the issue.

**Comment by notnotmelon** [comment]
I have rewritten all code related to this. Please open a new ticket if this is still an issue.

**Comment by DoomSquirter** [comment]
> > I'm more than capable of just putting them in there myself.
> 
> The whole point is to have it request bots when you are in remote view on another planet.

oh that makes a lot of sense.  so you can construct things remotely, etc.  I haven't gotten to space yet so I didn't see the point.

Thanks very much for the clarification
