### ISSUE TITLE
followup to roboports in factories

### ISSUE THREAD

**Issue by DoomSquirter** [notnotmelon/factorissimo-2-notnotmelon#79]
referencing #67 and #75

So, to followup, I updated to latest which includes your fixes from #75 

The fix works.  my personal bots don't enter the factories anymore from the outside.

Now, I get these notifications that I can't cancel
![image](https://github.com/user-attachments/assets/cb90ee1a-44bc-439d-b41e-c8afe2ba67dc)

and as a example, I go into a factory I put 10 robots in previously, but it's requesting another 10 in another place
![image](https://github.com/user-attachments/assets/af033f70-7bea-49e5-ab1e-938aa7f6096e)

in addition, with them setup, since I added construction robots in the factory, anytime I am working in that factory and I deconstruct something, randomly, one of the factory bots will pick up the item(s) and put in the storage chest

if I set the storage chest to have no open slots and I had turned off my personal roboport, the factory bots come out, pick up the items then hover there in place

I understand I'm probably not using this setup as I should but up until now I haven't even started placing roboports down and I don't have a good setup yet, so it seems like you have to have a sufficient setup on the outside to accomodate what the upgrade does

and until you do, you're hampered by this setup cause there's no way to disable the behavior till you setup a fully functioning roboport storage setup

hindsight is 20/20 and I probably should have not researched this upgrade till after I had a good setup going to accomodate it

**Comment by DoomSquirter** [comment]
so, update to issue

I went to a couple factories and got it to clear the 10 requests from each factory.  I only did a couple

saved my game and quit to main then loaded it

It did not repeat this on the ones I had "fixed" the request in on previous load.  so maybe this works as you intended as far as that part goes?

**Comment by notnotmelon** [comment]
Related: https://github.com/notnotmelon/factorissimo-2-notnotmelon/discussions/77
