### ISSUE TITLE
power in factory doesn't seem to actually disconnect from outside power

### ISSUE THREAD

**Issue by DoomSquirter** [notnotmelon/factorissimo-2-notnotmelon#85]
so I saw #60 and thought I could disable the power using a power switch to the factory 
I have a 6xreactor with turbines inside a t3 factory

but I noticed that it still sees the power network inside even tho it's disconnected to power network

![image](https://github.com/user-attachments/assets/d5951615-f7fe-4d0a-94c3-0b2c7a5cb0c2)

and this is the power thing inside the factory

![image](https://github.com/user-attachments/assets/e19c0b0a-f10f-4d6b-a1e7-29a32cd3f6a5)

when I used the power switch it didn't seem like it did anything and I was thinking maybe this is why?

using factorissimo-2-notnotmelon_3.5.9

**Comment by DoomSquirter** [comment]
I caught the first pic in the non blinking state.  sorry for the confusion.  consider this a replacement for the first pic

![image](https://github.com/user-attachments/assets/64c63cbf-3a5b-4537-ac9d-c8a7bb96a8cd)

**Comment by notnotmelon** [comment]
What happens if you mine it and build it back?

**Comment by DoomSquirter** [comment]
That fixes it.  it respects the new power connection/switch and turns on/off.  thanks alot.  closing this.
