### ISSUE TITLE
mod compatibility - put construction robot upgrade behind a mod setting

### ISSUE THREAD

**Issue by DanPli** [notnotmelon/factorissimo-2-notnotmelon#86]
If using a mod that changes construction robots (remove vanilla ones, replacing them with tiers of drones), the research that unlocks factorissimos construction robots upgrade will cause never-ending logistic alerts, since the logistic request for the vanilla drones can never be fulfilled. Deleting the request manually in every building does not help, since it seems to come back automatically after a reload/restart.

Please make that particular technology optional via mod setting.

Thanks :)

**Comment by JamesMDenton** [comment]
Have you found any way to fix this? Having most of my map flashing and the constant unfulfilled requests is really bad. And I've progressed WAY to far to roll back before the technology

**Comment by DancingDolphins** [comment]
I have the same question too

**Comment by MaxAstro** [comment]
> Have you found any way to fix this? Having most of my map flashing and the constant unfulfilled requests is really bad. And I've progressed WAY to far to roll back before the technology

If you are comfortable editing the mod's scripts, you can fix this by finding the file robotport.lua in the folder Scripts, finding the function set_default_roboport_construction_robot_request, and replace the entire content of that function with just:

`local function set_default_roboport_construction_robot_request
return 0
end`

That will make the alerts go away.

**Comment by Toys0125** [comment]
I agree it should be a mod setting because it would be up to the mod authors of the bot mods to add support for factorissimo.

**Comment by MaxAstro** [comment]
Honestly, rather than the tech itself being a mod setting, whether or not the factories automatically request robots should be a setting.

The tech works fine with modded bots.

**Comment by JamesMDenton** [comment]
> Honestly, rather than the tech itself being a mod setting, whether or not the factories automatically request robots should be a setting.
> 
> The tech works fine with modded bots.

I 100% agree

**Comment by MaxAstro** [comment]
Just wanted to mention, after updating to 3.5.18, I'm still getting the alerts coming back after changing which mods are enabled.

**Comment by JamesMDenton** [comment]
> > Have you found any way to fix this? Having most of my map flashing and the constant unfulfilled requests is really bad. And I've progressed WAY to far to roll back before the technology
> 
> If you are comfortable editing the mod's scripts, you can fix this by finding the file robotport.lua in the folder Script inside the mod zip file, finding the function set_default_roboport_construction_robot_request, and replace the entire content of that function with just:
> 
> ```lua
> local function set_default_roboport_construction_robot_request(roboport, count)
> return 0
> end
> ```
> 
> That will make the alerts go away.

Plus I can't update to 3.5.18 without my game crashing after using this fix, even if I don't reapply the fix (and also if I do). I get an attempt to index field event error.
