### ISSUE TITLE
Compatibility Error with Factorio+

### ISSUE THREAD

**Issue by Tellik** [notnotmelon/factorissimo-2-notnotmelon#88]
Factorio+ (1.5.1) uses an entity prototype "factory-1" which causes it to be registered twice causing a conflict with Factorissimo (3.5.13) preventing both from being used.

I'm hoping a simple rename on either end should resolve this issue.

**Comment by notnotmelon** [comment]
I will not rename the factory-1 prototype.
Due to heavily scripted mechanics, this rename migration will be extremely difficult and error-prone.
Hopefully fishbus can resolve it on the other side.

**Comment by Tellik** [comment]
I took a look at it on your side, then took a look at it on his side.

... I definitely agreed with you. It took all of a half dozen quick edits to fix the issue on his end. 

I also alerted them to the issue on their end as well, I just wanted to make you aware of it, as well as anyone else who might run into this issue in the future if it doesn't get fixed.
