### ISSUE TITLE
allow change of roboport research to come in line with early bots

### ISSUE THREAD

**Issue by insanlypoor** [notnotmelon/factorissimo-2-notnotmelon#89]
i use robot wworld and robot world continued mods. for me this would be with red and green science

**Comment by notnotmelon** [comment]
I will not do this.

The factory construction upgrade is intended for use on other planets and remote view. Indeed it has certain compromises when researched for example additional alerts requesting construction bots.

Space science is much easier to obtain in space age, I recommend playing a bit more and having a dedicated roboport network before using this feature.
