### ISSUE TITLE
Gleba factory floor(and potentially others) bug out when using rso

### ISSUE THREAD

**Issue by tigartar** [notnotmelon/factorissimo-2-notnotmelon#91]
![image](https://github.com/user-attachments/assets/17196c47-a3bd-4a9d-8fd6-52d0c4b2268c)

https://mods.factorio.com/mod/rso-mod mod in question

When rso is active and a factory floor is generated a default grass biome gets created alongside it that the player can walk over and build in BUT you loose the greenhouse ability and other such things

If floor is generated before rso is enabled then they seem to work fine.

**Comment by notnotmelon** [comment]
Please run this command. It may take up to 15 minutes.

```/c for _, surface in pairs(game.surfaces) do if surface.name:find("%-factory%-floor$") or surface.name:find("^factory%-floor%-%d+$") then surface.freeze_daytime = true if remote.interfaces["RSO"] then pcall(remote.call, "RSO", "ignoreSurface", surface.name) end local mgs = surface.map_gen_settings mgs.width = 2 mgs.height = 2 surface.map_gen_settings = mgs local grass_1 = surface.find_tiles_filtered {name = "grass-1"} local new_tiles = {} for _, tile in pairs(grass_1) do table.insert(new_tiles, {name = "out-of-map", position = tile.position}) end surface.set_tiles(new_tiles) end end```

If you prefer to keep achievements, run the command in via this mod (you have to remove /c at the start)
https://mods.factorio.com/mod/some-luaconsole?from=search
