### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DragonMaster14545** [notnotmelon/factorissimo-2-notnotmelon#92]
Hi, I am getting this crash on startup, using binary search I was able to figure out that it is a problem with this mod
![image.png](https://github.com/user-attachments/assets/46d0f859-af81-4c90-8cc8-90e401740944)

**Comment by Toys0125** [comment]
You need to provide more information. The log file that is indicated in the error prompt would help a long way in determining the problem. Otherwise, this won't help at all.

**Comment by notnotmelon** [comment]
Update factorio.
